---
# tasks file for tes
- name: Install apache httpd
  ansible.builtin.apt:
    name: apache2
    state: present
    update_cache: yes
- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: tes/files/main.yml
    dest: /var/www/html
    owner: root
    group: root
    mode: '0644'
